name: app_pokedex_widgetbook
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  feature_pokedex_widgetbook:
    path: ../../features/feature_pokedex_widgetbook
  design:
    path: ../../design

  cupertino_icons: 1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0

flutter:
  uses-material-design: true